export const ADD_COURSE_ENROLL = 'ADD_COURSE_ENROLL';
export const GET_COURSE_ENROLL = 'GET_COURSE_ENROLL';
export const DELETE_COURSE_ENROLL = 'DELETE_COURSE_ENROLL';
export const COURSE_ENROLL_LOADING = 'COURSE_ENROLL_LOADING';
export const COURSE_ENROLL_NOT_FOUND = 'COURSE_ENROLL_NOT_FOUND';
export const GET_COURSE_ENROLLS = 'GET_COURSE_ENROLLS';

export const ADD_COURSE = 'ADD_COURSE';
export const GET_COURSE = 'GET_COURSE';
export const DELETE_COURSE = 'DELETE_COURSE';
export const COURSE_LOADING = 'COURSE_LOADING';
export const COURSE_NOT_FOUND = 'COURSE_NOT_FOUND';
export const GET_COURSES = 'GET_COURSES';