export const ADD_CATEGORY = 'ADD_CATEGORY';
export const GET_CATEGORY = 'GET_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const CATEGORY_LOADING = 'CATEGORY_LOADING';
export const CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND';
export const GET_CATEGORYS = 'GET_CATEGORYS';